package audit

// Rules is the explicit method/route allowlist; reads, polling and tokens are excluded.
func Rules() []Rule {
	return []Rule{
		{Method: "POST", Route: "/api/auth/login/password", Action: "auth.login.password", TargetType: "user", AuthMethod: "password"},
		{Method: "POST", Route: "/api/auth/login/email", Action: "auth.login.email", TargetType: "user", AuthMethod: "email_otp"},
		{Method: "POST", Route: "/api/auth/email/send", Action: "auth.email.send", TargetType: "user"},
		{Method: "POST", Route: "/api/auth/qr/scan", Action: "auth.qr.scan", TargetType: "user"},
		{Method: "POST", Route: "/api/auth/qr/confirm", Action: "auth.qr.confirm", TargetType: "user"},
		{Method: "POST", Route: "/api/auth/qr/complete", Action: "auth.login.qr", TargetType: "user", AuthMethod: "qr_code"},
		{Method: "POST", Route: "/api/auth/logout", Action: "auth.logout", TargetType: "user"},
		{Method: "GET", Route: "/api/auth/third/:provider", Action: "auth.third_party.start", TargetType: "provider", TargetParam: "provider"},
		{Method: "GET", Route: "/api/auth/third/:provider/callback", Action: "auth.login.third_party", TargetType: "user"},
		{Method: "GET", Route: "/oauth/authorize", Action: "oauth.authorize", TargetType: "oauth_client"},
		{Method: "POST", Route: "/api/user/register", Action: "user.register", TargetType: "user"},
		{Method: "POST", Route: "/api/user/password/reset", Action: "user.password.reset", TargetType: "user"},
		{Method: "PUT", Route: "/api/user/profile", Action: "user.profile.update", TargetType: "user"},
		{Method: "PUT", Route: "/api/user/password", Action: "user.password.update", TargetType: "user"},
		{Method: "POST", Route: "/api/user/avatar", Action: "user.avatar.update", TargetType: "user"},
		{Method: "POST", Route: "/api/user/emails", Action: "user.email.add", TargetType: "email"},
		{Method: "POST", Route: "/api/user/emails/verification/confirm", Action: "user.email.verify", TargetType: "email"},
		{Method: "POST", Route: "/api/user/emails/:id/verification", Action: "user.email.verification.send", TargetType: "email", TargetParam: "id"},
		{Method: "PUT", Route: "/api/user/emails/:id/primary", Action: "user.email.primary", TargetType: "email", TargetParam: "id"},
		{Method: "DELETE", Route: "/api/user/emails/:id", Action: "user.email.delete", TargetType: "email", TargetParam: "id"},
		{Method: "DELETE", Route: "/api/user/devices/:device_id", Action: "user.device.revoke", TargetType: "device", TargetParam: "device_id"},
		{Method: "GET", Route: "/api/user/third/:provider/bind", Action: "user.third_party.start", TargetType: "provider", TargetParam: "provider"},
		{Method: "POST", Route: "/api/user/third/bindings/:binding_id/confirm", Action: "user.third_party.bind", TargetType: "provider"},
		{Method: "DELETE", Route: "/api/user/third/:provider", Action: "user.third_party.unbind", TargetType: "provider", TargetParam: "provider"},
		{Method: "POST", Route: "/api/user/passkeys/registration/email/send", Action: "user.passkey.email.send", TargetType: "user"},
		{Method: "POST", Route: "/api/user/passkeys/registration/options", Action: "user.passkey.registration.start", TargetType: "user"},
		{Method: "POST", Route: "/api/user/passkeys/registration/verify", Action: "user.passkey.create", TargetType: "passkey"},
		{Method: "PATCH", Route: "/api/user/passkeys/:id", Action: "user.passkey.rename", TargetType: "passkey", TargetParam: "id"},
		{Method: "DELETE", Route: "/api/user/passkeys/:id", Action: "user.passkey.delete", TargetType: "passkey", TargetParam: "id"},
		{Method: "POST", Route: "/api/user/reauth/passkey/options", Action: "user.reauth.passkey.start", TargetType: "user", AuthMethod: "passkey"},
		{Method: "POST", Route: "/api/user/reauth/passkey/verify", Action: "user.reauth.passkey.verify", TargetType: "user", AuthMethod: "passkey"},
		{Method: "POST", Route: "/api/user/reauth/email/send", Action: "user.reauth.email.send", TargetType: "user", AuthMethod: "email_otp"},
		{Method: "POST", Route: "/api/user/reauth/email/verify", Action: "user.reauth.email.verify", TargetType: "user", AuthMethod: "email_otp"},
		{Method: "POST", Route: "/api/admin/oauth-clients", Action: "admin.client.create", TargetType: "oauth_client"},
		{Method: "PUT", Route: "/api/admin/oauth-clients/:id", Action: "admin.client.update", TargetType: "oauth_client", TargetParam: "id"},
		{Method: "POST", Route: "/api/admin/oauth-clients/:id/logo", Action: "admin.client.logo.update", TargetType: "oauth_client", TargetParam: "id"},
		{Method: "DELETE", Route: "/api/admin/oauth-clients/:id/logo", Action: "admin.client.logo.clear", TargetType: "oauth_client", TargetParam: "id"},
		{Method: "GET", Route: "/api/admin/oauth-clients/:id/secret", Action: "admin.client.secret.view", TargetType: "oauth_client", TargetParam: "id"},
	}
}
